### ISSUE TITLE
Late initialization of image structs

### ISSUE THREAD

**Issue by ardiama** [OpenImageDebugger/OpenImageDebugger#106]
Thank you very much for providing this long-missing plugin.
I am using it in C and remote GDB.
I see the following issue:
1. I define a pointer to an image structure, but do not allocate memory (at this point the pointer points to 0x000.
2. Later in my program I allocate memory and now the pointer points to valid memory.
3. When OID starts, I try to inspect the image structure. But OID tries to access the initial address (0x0000)  and not the updated one.

It looks like OID does not refresh all symbols upon breakpoint stop, so it cannot "discover" pointer updates?
I understand this would take too long if done in every step, but maybe a button on the GUI could be added to refresh all symbols on demand?

Extract from GDB console:
253,314 ~"[OpenImageDebugger] Error: Could not plot variable\n"
253,314 ~"Cannot access memory at address 0x4\n"
253,315 &"Traceback (most recent call last):\n"
253,315 &"  File \"/usr/local/OpenImageDebugger/oidscripts/oidwindow.py\", line 211, in __call__  buffer_metadata = self._bridge.get_buffer_metadata(self._variable)\n"
253,315 &"  File \"/usr/local/OpenImageDebugger/oidscripts/debuggers/gdbbridge.py\", line 59, in get_buffer_metadata\n    buffer_metadata = self._type_bridge.get_buffer_metadata(\n"
253,315 &"  File \"/usr/local/OpenImageDebugger/oidscripts/typebridge.py\", line 40, in get_buffer_metadata\n    return module.get_buffer_metadata(symbol_name,\n"
253,316 &"  File \"/usr/local/OpenImageDebugger/oidscripts/oidtypes/ImageC.py\", line 23, in get_buffer_metadata\n    width = int(picked_obj['noCols'])\n"
253,316 &"gdb.MemoryError: Cannot access memory at address 0x4\n"

**Comment by brunoalr** [comment]
Hi @ardiama, thanks for the kind words and reporting this. In order to be easier to help you, can you provide a minimal example in C + the custom type python script?

**Comment by ardiama** [comment]
Hello @brunoalr . I just tried to create an example. I am embarrassed to say that the issue is not there. The pointers update as they should. The error must be on my side. I should close the issue. 
Please accept my apologies for disturbing you, my project is rather huge and I must have missed something. 
But THANK you again for providing this.

**Comment by brunoalr** [comment]
No problem at all! The whole point of having OID open source is to help people with similar needs :D If you encounter this issue again, or any other, feel free to report them :)
