### ISSUE TITLE
An error occurred while compiling

### ISSUE THREAD

**Issue by CTYsimple** [OpenImageDebugger/OpenImageDebugger#136]
Hello, I had some errors when compiling version 1.9.7. My system is Ubuntu20.04, and the python version is 3.9. The QT version is 5.12. I cannot use the source code to compile. There are errors like the ones in the attachment. I followed them exactly. Configuration according to the installation manual, but some unexpected situations occurred.

Specific error:

```
/usr/bin/ld: /usr/local/lib/libpython3.9.a(boolobject.o): **relocation R_X86_64_PC32 against symbol `_Py_FalseStruct' can not be used when making a shared object; recompile with -fPIC**
/usr/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/oidbridge/CMakeFiles/oidbridge_python3.dir/build.make:177：src/oidbridge/liboidbridge_python3.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:170：src/oidbridge/CMakeFiles/oidbridge_python3.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

```
I tried adding the compilation option add_compile_options(-fPIC) to the CMakeLists script, but it didn't work. 

I tried to use the software compiled by the author directly, but the error said that I could not find the so library of QT5.15, the QT version you compiled was 5.15, and some of my environment relied on QT5.12, which was inconvenient to replace.

I think it is better to use the source code to compile, do you have relevant suggestions? Thank you very much

**Comment by CTYsimple** [comment]
![屏幕截图 2023-11-10 094529](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/95261677/265b57a8-b605-4fef-b74e-a205fc86eedb)

**Comment by CTYsimple** [comment]
![Uploading 屏幕截图 2023-11-10 103422.png…]()

**Comment by CTYsimple** [comment]
![屏幕截图 2023-11-10 103422](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/95261677/860680cf-843a-4b8b-bcc2-226204d0d828)
__

**Comment by brunoalr** [comment]
Hi @CTYsimple, thanks for providing the versions information.

For logs and code, please don't post screenshots. Post the formatted text as you did in the first message.

I haven't seen this error myself.

Due to limited resources, we only support Qt 5.15 and the default version and installation of the remaining dependencies and tools that come with an Ubuntu LTS release. For Ubuntu 20.04 that means python and libpython 3.8.

It looks weird that the compiler is trying to link against a static version of libpython. Can you double check if you have a dynamic version of libpython installed?

**Comment by CTYsimple** [comment]
Thank you. I have received your suggestion. I will first check my relevant questions according to your suggestion.

**Comment by CTYsimple** [comment]
Hi @brunoalr, I have installed and configured the software according to your suggestion. The above problem is due to the wrong python version of my virtual machine. Ubuntu comes with python3.8, but it doesn't seem to work. I solved this problem by installing the python3.9 version. Thank you for your contribution to the open source community. This software is very useful!

**Comment by brunoalr** [comment]
Hi, @CTYsimple, glad that you found out a solution and thanks for sharing it here :)
