### ISSUE TITLE
Error while building with Qt < 5.11

### ISSUE THREAD

**Issue by dakhouya** [OpenImageDebugger/OpenImageDebugger#170]
### Environment

- OID version (commit or tag): accda165dd6c9a378c4fd8fef6e36a4565955b51
- OS and Version: ubuntu 18.04
- Which debugger [gdb and/or lldb] and respective versions: gdb
- Python version: 3.6.9

### Describe the bug

While building in my environment, I'm getting compilation errors regarding horizontalAdvance when using Qt < 5.11
According to Qt horizontalAdvance was introduce in Qt 5.11 https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance
In the OpenImageDebugger documentation the requirements state that we should use Qt 5.6+.

### To Reproduce

```
git clone https://github.com/OpenImageDebugger/OpenImageDebugger.git
cd OpenImageDebugger
git submodule init
git submodule update

cmake -S . -B build -DCMAKE_INSTALL_PREFIX=./install
cmake --build build --config Release --target install -j 4
```

### Expected behavior

Build complete

### Actual behavior

Build fail

### Error messages/stack traces

```
/opt/OpenImageDebugger/src/ui/gl_text_renderer.cpp: In member function ‘void GLTextRenderer::generate_glyphs_texture()’:
/opt/OpenImageDebugger/src/ui/gl_text_renderer.cpp:168:31: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int advance_x     = g.horizontalAdvance(*p);
                               ^~~~~~~~~~~~~~~~~
/opt/OpenImageDebugger/src/ui/gl_text_renderer.cpp:196:27: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         int advance_x = g.horizontalAdvance(*p);
```

**Comment by dakhouya** [comment]
If the support for old version of Qt is wanted, something like this could do the job.

```
diff --git a/src/ui/gl_text_renderer.cpp b/src/ui/gl_text_renderer.cpp
index 89362bf..d682009 100644
--- a/src/ui/gl_text_renderer.cpp
+++ b/src/ui/gl_text_renderer.cpp
@@ -165,7 +165,11 @@ void GLTextRenderer::generate_glyphs_texture()
     const int cropped_bitmap_height = real_ascent - real_descent;
 
     for (p = reinterpret_cast<const unsigned char*>(text); *p; p++) {
-        int advance_x     = g.horizontalAdvance(*p);
+        #if QT_VERSION >= QT_VERSION_CHECK(5, 11, 0)
+            int advance_x     = g.horizontalAdvance(*p);
+        #else
+            int advance_x     = g.width(*p);
+        #endif
         int bitmap_height = g.height();
 
         text_texture_advances[*p][0] = advance_x;
@@ -193,7 +197,11 @@ void GLTextRenderer::generate_glyphs_texture()
 
     int x = 0;
     for (p = reinterpret_cast<const unsigned char*>(text); *p; p++) {
-        int advance_x = g.horizontalAdvance(*p);
+        #if QT_VERSION >= QT_VERSION_CHECK(5, 11, 0)
+            int advance_x     = g.horizontalAdvance(*p);
+        #else
+            int advance_x     = g.width(*p);
+        #endif
 
         text_texture_offsets[*p][0] = x + border_size;
         text_texture_offsets[*p][1] = real_descent + border_size;
```

If needed I don't mind opening a PR.

**Comment by brunoalr** [comment]
Hi, @dakhouya , thanks for opening the bug and posting a solution. I don't plan on supporting multiple qt versions - in fact I am considering switching to something as portable as qt, such as https://github.com/ocornut/imgui - but since this fix is minimal, a pull request is more than welcome :D

**Comment by dakhouya** [comment]
@brunoalr with the latest changes which required Qt 5.12.8+ in cmake, I think this issue can be close.

**Comment by brunoalr** [comment]
@dakhouya yeah, it makes sense. but thanks a lot anyways :D It's just that I have only so much bandwidth and lately I am the only one maintaining the project, so I have to impose some limitations. The sad part is that I don't have a strong background in CG as @csantosbh has, so I prefer to improve code quality and developer experience :) if you have any feature you would like to contribute feel free to chime in

**Comment by dakhouya** [comment]
I'm not sure if I have much time yet, but lets see! 
Thanks for your work on this project btw!
