### ISSUE TITLE
Invalid plotting of OpenCV matrices

### ISSUE THREAD

**Issue by wl2776** [OpenImageDebugger/OpenImageDebugger#215]
### Environment

- OID version (commit or tag): head of main branch (b151cd96)
- OS and Version: 
  Ubuntu 22.04 with all updates.
  ```
  ❯ uname -a
   Linux omen 6.5.0-17-generic #17~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan 16 14:32:32 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Which debugger [gdb and/or lldb] and respective versions:
   ```
   ❯ gdb --version
   GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
   Copyright (C) 2022 Free Software Foundation, Inc.
   License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
   This is free software: you are free to change and redistribute it.
   There is NO WARRANTY, to the extent permitted by law.
   ```

- Python version: 3.10.12

### Describe the bug

1. Screwed markup of pixel values for matrices of odd size (7x7, 15x15)
   ![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/4774284/117d8e67-9716-4a4f-95ba-1722e370771a) ![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/4774284/1fefac1a-1a0b-420b-a33c-96a2fea67237)

   At the same time matrices of even sizes (10x10, 16x16) are displayed correctly
   ![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/4774284/61a7ae1e-3853-47a0-b1d6-60e17fe38830)![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/4774284/326eea80-84d9-45fd-915a-7ff3d23fcdad)

2. Matrices do not appear in the left column of the OID window  (the one that is below "add symbols" input box) on pressing Enter. They appear in that window after clicking on that left column with a mouse or pressing Tab key or switching to another window with Alt-Tab.

### To Reproduce

1. clone and build https://github.com/wl2776/oid_debug_sample (it uses [Conan](https://conan.io) for handling project dependencies. See README.md inside)
2. ```
   $ cd build
   $ make -j
   $ gdb sample
   Reading symbols from sample...
   (gdb) source /usr/local/OpenImageDebugger/oid.py
   [OpenImageDebugger] Info: Could not activate hooks for any IDEs
   (gdb) break 19
   Breakpoint 1 at 0x37731: file /home/wl2776/work/oid_debug_sample/sample.cpp, line 19.
   (gdb) run
   Starting program: /home/wl2776/work/oid_debug_sample/build/sample
   [Thread debugging using libthread_db enabled]
   Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

   Breakpoint 1, main () at /home/wl2776/work/oid_debug_sample/sample.cpp:19
   19          mh.update();
   ```
4. Switch to OID window and enter `mh.v[0]`, then `mh.v[1]`
    **The bug**: matrices do not appear in the left list after entering their names and pressing Enter. They appear after click on this list column with left mouse button, or pressing Tab key, or switching to another window with Alt-Tab.

5. Click on `mh.v[1]` in the left column to see its details. You see first figure above. Click on `mh.v[0]`. You see the second figure above.

6. GDB console shows:
   ```
   (gdb) 0x5555558aeb80:   0x00000000
   0x5555558aee00: 0x3f800000
   (gdb) n
   20          return 0;
   ```

### Expected behavior

Matrices appear in the list below `add symbols` input box immediately after a user presses Enter.
Pixel values are shown inside pixels.

### Actual behavior

See bug description

### Error messages/stack traces

No errors

### Screenshots

See bug description.

### Additional context

I've tried to fix it myself, but I'm not familiar with Qt at this level. Also, it is still not very clear for me, how python inside a debugger communicates with the Qt application (I've realized that they use TCP, but other details are still hidden from me).

**Comment by brunoalr** [comment]
thanks for the report! I will check it when I have time. I guess it is probably related to a bunch of static_casts that I added in the past months. My plan is to first try to bisect the commits and check what is going on.

> I've tried to fix it myself, but I'm not familiar with Qt at this level. Also, it is still not very clear for me, how python inside a debugger communicates with the Qt application (I've realized that they use TCP, but other details are still hidden from me).

At some point I also want to create an architecture diagram, but I won't promise any dates. However, seeing that it would be useful for contributors like you motivates me a lot to do it :D

**Comment by brunoalr** [comment]
I managed to reproduce the issue and bisect it. And, of course the issue would come from a big bang commit I thought it was fine: 568208ee9f84c97ff94933c7a4c4b84a557547c8 ... It will take me sometime to find where exactly I screwed up.

In the meantime, you could use v1.11.2, which I expect not to be buggy.

**Comment by brunoalr** [comment]
> One more useful feature for me would be an option to choose transport layer.

> My macbook has corporate software installed, that sometimes blocks TCP ports, and the debugger cannot communicate with its Qt counterpart.

Thanks for the suggestion, I will keep that in mind. I was thinking about experimenting with grpc at some point, but I have no idea about performance.
