### ISSUE TITLE
Use better approach for logging in python

### ISSUE THREAD

**Issue by brunoalr** [OpenImageDebugger/OpenImageDebugger#4]
we should look for an error logging library and use fixed tags instead of ad hoc messages

_Originally posted by @brunoalr in https://github.com/OpenImageDebugger/OpenImageDebugger/pull/1_

**Comment by brunoalr** [comment]
https://docs.python.org/3.8/library/logging.html

**Comment by dakhouya** [comment]
I just open a PR for this one https://github.com/OpenImageDebugger/OpenImageDebugger/pull/227
Since this issue is quite old, if you have an other idea in mind, let me know!

**Comment by brunoalr** [comment]
Solved by #227
