### ISSUE TITLE
Add support to VSCode WSL remote

### ISSUE THREAD

**Issue by binfsuc** [OpenImageDebugger/OpenImageDebugger#82]
I am using vscode+wsl2 on windows, I install OpenImageDebugger successfully, and run python3 /path/to/OpenImageDebugger/oid.py --test  can see the Open Image Debugger window with the buffers sample_buffer_1 and sample_buffer_2.   I modified. ~/.gdbinit  with add "source /path/to/OpenImageDebugger/oid.py",  all is ok,  I wirte a c++ demo only read and show a image with opencv, When the debugger hits a breakpoint, the Open Image Debugger window  is not  opened. what's the problem? Can someone help me.
![QQ截图20230612104005](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/dd8586a6-0b22-4f84-9c36-8bdcad328c0a)

**Comment by brunoalr** [comment]
Hi @binfsuc, I haven't tested debugging with VSCode + WSL. My *guess* is that VSCode is not configured to use the same gdb binary as the one from WSL.

Can you share all the project files from this C++ demo, please? (CMake-related files, source code and launch.json)

**Comment by binfsuc** [comment]
> Hi @binfsuc, I haven't tested debugging with VSCode + WSL. My _guess_ is that VSCode is not configured to use the same gdb binary as the one from WSL.
> 
> Can you share all the project files from this C++ demo, please? (CMake-related files, source code and launch.json)
Thank you. If it is what you said, how should I modify it
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/8b6f0c97-263d-49b8-ac6f-e6348123716d)
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/d1ea9b90-3093-4af5-9740-040140e9ad0a)
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/f7f1868e-82b9-457d-b0d3-5d8bdacd9c42)

**Comment by brunoalr** [comment]
Hi @binfsuc if you can share them as files and/or text it gets easier for me to help :)

**Comment by binfsuc** [comment]
@brunoalr  ok ，this is all file
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/25629cdf-7703-40bf-b263-df14346e6a8b)

[myprojects.zip](https://github.com/OpenImageDebugger/OpenImageDebugger/files/11718318/myprojects.zip)

**Comment by brunoalr** [comment]
Thanks! I will try to reproduce it later and let you know.

**Comment by binfsuc** [comment]
ok
my ./gdbinit
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/e05b3716-f7c9-4b39-a623-7b5c54b0374b)
run python3 /path/to/OpenImageDebugger/oid.py --test 
![image](https://github.com/OpenImageDebugger/OpenImageDebugger/assets/22810349/a756998e-4713-4c49-905c-d8ec0f5c75ec)

**Comment by binfsuc** [comment]
[is there any progress?

**Comment by brunoalr** [comment]
I also did one final test, in the same setup (Windows 10 + WSL2 + MobaXterm's X11 server) I installed vscode *inside* WSL and I can confirm it works.

**Comment by brunoalr** [comment]
Another test: I was able to get access to a Windows 10 22H2 with WSLg support and managed to get OID to work when connecting to a WSL remote on VSCode running on the host machine. Make sure you `source oid.py` correctly, for example via `~/.gdbinit`.
